# Site settings
title: The Payroll Centre
email: your-email@domain.com
description: The Payroll Centre
baseurl:

#url: "http://www.artbymarie.info"

#collections:
#  links:
#    output: true


# Build settings
markdown: kramdown

sass:
  sass_dir: /_scss
